/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tetris.gui;
import java.awt.event.KeyEvent;
/**
 *
 * @author IPT
 */
public class GraphicsTetrisDialog extends javax.swing.JDialog {



    /**
     * Creates new form TextTetrisDialog
     */
    public GraphicsTetrisDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();               
        setLocationRelativeTo(null);
        tetrisGame1.setpontos(pontos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btUp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btLeft = new javax.swing.JButton();
        btDown = new javax.swing.JButton();
        btRight = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        spLines = new javax.swing.JSpinner();
        spColumns = new javax.swing.JSpinner();
        btCreate = new javax.swing.JButton();
        pontos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tetrisGame1 = new tetris.lib.game.TetrisGame();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(2, 3, 5, 5));
        jPanel3.add(jLabel1);

        btUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tetris/resources/up.png"))); // NOI18N
        btUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpActionPerformed(evt);
            }
        });
        jPanel3.add(btUp);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jLabel2);

        btLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tetris/resources/left.png"))); // NOI18N
        btLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLeftActionPerformed(evt);
            }
        });
        jPanel3.add(btLeft);

        btDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tetris/resources/down.png"))); // NOI18N
        btDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDownActionPerformed(evt);
            }
        });
        jPanel3.add(btDown);

        btRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tetris/resources/right.png"))); // NOI18N
        btRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRightActionPerformed(evt);
            }
        });
        jPanel3.add(btRight);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1, 5, 5));

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        spLines.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        spLines.setModel(new javax.swing.SpinnerNumberModel(20, 8, null, 1));
        spLines.setBorder(javax.swing.BorderFactory.createTitledBorder("Linhas"));
        jPanel4.add(spLines);

        spColumns.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        spColumns.setModel(new javax.swing.SpinnerNumberModel(10, 5, null, 1));
        spColumns.setBorder(javax.swing.BorderFactory.createTitledBorder("Colunas"));
        jPanel4.add(spColumns);

        jPanel2.add(jPanel4);

        btCreate.setBackground(new java.awt.Color(0, 0, 0));
        btCreate.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        btCreate.setForeground(new java.awt.Color(255, 255, 255));
        btCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tetris/resources/tetris.png"))); // NOI18N
        btCreate.setText("CREATE ");
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });
        jPanel2.add(btCreate);

        pontos.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        pontos.setForeground(new java.awt.Color(255, 255, 255));
        pontos.setText("Pontos: ");
        jPanel2.add(pontos);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("TETRIS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        tetrisGame1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tetrisGame1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout tetrisGame1Layout = new javax.swing.GroupLayout(tetrisGame1);
        tetrisGame1.setLayout(tetrisGame1Layout);
        tetrisGame1Layout.setHorizontalGroup(
            tetrisGame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        tetrisGame1Layout.setVerticalGroup(
            tetrisGame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(tetrisGame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpActionPerformed
        tetrisGame1.rotate();
        
    }//GEN-LAST:event_btUpActionPerformed

    private void btLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLeftActionPerformed
        tetrisGame1.moveLeft();
        
    }//GEN-LAST:event_btLeftActionPerformed

    private void btDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDownActionPerformed
        tetrisGame1.moveDown();                        
        if (!tetrisGame1.canMovePiece(1, 0)) {
            tetrisGame1.freezePiece();
            tetrisGame1.generateRandomPiece();
        }        
    }//GEN-LAST:event_btDownActionPerformed

    private void btRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRightActionPerformed
        tetrisGame1.moveRight();
        
    }//GEN-LAST:event_btRightActionPerformed

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        int lines = (Integer) spLines.getValue();
        int cols = (Integer) spColumns.getValue();
        tetrisGame1.resize(lines, cols); 
        pontos.setText("Pontos: ");
    }//GEN-LAST:event_btCreateActionPerformed
    //     if(evt.getKeyCode() == KeyEvent.VK_UP){
    //       tetrisGame1.rotate();
    // }else if (evt.getKeyCode() == KeyEvent.VK_RIGHT){
    //        tetrisGame1.moveRight();
    //  }else if (evt.getKeyCode() == KeyEvent.VK_LEFT){
    //   tetrisGame1.moveLeft();
    // }else if (evt.getKeyCode() == KeyEvent.VK_DOWN){
    //        tetrisGame1.moveDown();
    //   }else if (evt.getKeyCode() == KeyEvent.VK_Z){
    //     tetrisGame1.fallDown();
    // }

    private void tetrisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tetrisKeyPressed
        
   //     if(evt.getKeyCode() == KeyEvent.VK_UP){
     //       tetrisGame1.rotate();
       // }else if (evt.getKeyCode() == KeyEvent.VK_RIGHT){
    //        tetrisGame1.moveRight();
      //  }else if (evt.getKeyCode() == KeyEvent.VK_LEFT){
         //   tetrisGame1.moveLeft();
       // }else if (evt.getKeyCode() == KeyEvent.VK_DOWN){
    //        tetrisGame1.moveDown();
     //   }else if (evt.getKeyCode() == KeyEvent.VK_Z){
       //     tetrisGame1.fallDown();
   // }
    }//GEN-LAST:event_tetrisKeyPressed
    public void ShowjDialog1(){
        jDialog1.setVisible(true);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tetrisGame1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tetrisGame1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            tetrisGame1.rotate();
        }else if (evt.getKeyCode() == KeyEvent.VK_RIGHT){
            tetrisGame1.moveRight();
        }else if (evt.getKeyCode() == KeyEvent.VK_LEFT){
            tetrisGame1.moveLeft();
        }else if (evt.getKeyCode() == KeyEvent.VK_DOWN){
            tetrisGame1.moveDown();
        }else if (evt.getKeyCode() == KeyEvent.VK_Z){
            tetrisGame1.fallDown();
    }
                
    }//GEN-LAST:event_tetrisGame1KeyPressed

//    public void setPontosLabel(JLabel pontosLabel) {
   // this.pontos = pontosLabel;
 //   tetris.setPontos(pontosLabel);


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicsTetrisDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicsTetrisDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicsTetrisDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicsTetrisDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GraphicsTetrisDialog dialog = new GraphicsTetrisDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreate;
    private javax.swing.JButton btDown;
    private javax.swing.JButton btLeft;
    private javax.swing.JButton btRight;
    private javax.swing.JButton btUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel pontos;
    private javax.swing.JSpinner spColumns;
    private javax.swing.JSpinner spLines;
    private tetris.lib.game.TetrisGame tetrisGame1;
    // End of variables declaration//GEN-END:variables
}

