/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tetris.gui;

import tetris.lib.game.TetrisSounds;

/**
 *
 * @author IPT
 */
public class MainApp extends javax.swing.JFrame {

    private TetrisSounds tetrisSounds;
    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        setLocationRelativeTo(null);
        
        tetrisSounds = new TetrisSounds();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        btPlay1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        btRules = new javax.swing.JToggleButton();
        btAbout2 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tetris/gui/tumblr_inline_mh5ex485Kq1qijotv.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 0));
        jLabel5.setText("R");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 40, 40));

        jToggleButton1.setBackground(new java.awt.Color(51, 102, 255));
        jToggleButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 22)); // NOI18N
        jToggleButton1.setText("QUIT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 250, 30));

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("S");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 40, 40));

        btPlay1.setBackground(new java.awt.Color(255, 0, 0));
        btPlay1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        btPlay1.setForeground(new java.awt.Color(255, 255, 255));
        btPlay1.setText("PLAY");
        btPlay1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btPlay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlay1ActionPerformed(evt);
            }
        });
        getContentPane().add(btPlay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 250, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(77, 77, 255));
        jLabel2.setText("I");
        jLabel2.setMaximumSize(new java.awt.Dimension(48, 14));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 20, 40));

        btRules.setBackground(new java.awt.Color(255, 255, 0));
        btRules.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        btRules.setForeground(new java.awt.Color(255, 255, 255));
        btRules.setText("?");
        btRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRulesActionPerformed(evt);
            }
        });
        getContentPane().add(btRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 250, 50));

        btAbout2.setBackground(new java.awt.Color(51, 204, 0));
        btAbout2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        btAbout2.setForeground(new java.awt.Color(255, 255, 255));
        btAbout2.setText("ABOUT US");
        btAbout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbout2ActionPerformed(evt);
            }
        });
        getContentPane().add(btAbout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 250, 40));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("T");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 40, 40));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("E");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 40, 40));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("T");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 40, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tetris/gui/b021a3c2f1cad21be6e3dcb665a363ac.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPlay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlay1ActionPerformed
       new GraphicsTetrisDialog(this, true).setVisible(true);

    }//GEN-LAST:event_btPlay1ActionPerformed

    private void btRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRulesActionPerformed
        new RulesDialog(this, true).setVisible(true);
    }//GEN-LAST:event_btRulesActionPerformed

    private void btAbout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbout2ActionPerformed
        AboutDialog about = new AboutDialog(this, true);
        about.setLocationRelativeTo(btAbout2);
        about.setVisible(true);
    }//GEN-LAST:event_btAbout2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
           MainApp mainApp = new MainApp();
           new MainApp().setVisible(true);
           mainApp.setVisible(true);
           mainApp.tetrisSounds.MenuSound();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btAbout2;
    private javax.swing.JToggleButton btPlay1;
    private javax.swing.JToggleButton btRules;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
